export const FETCH_HOTELS = 'FETCH_HOTELS';
export const FETCH_CURRENT_HOTEL = 'FETCH_CURRENT_HOTEL';
export const FORCE_LOCATION_TAB = 'FORCE_LOCATION_TAB';
export const ON_TAB_CHANGE = 'ON_TAB_CHANGE';